-- INSTALACION DE IMAGENES Y CONTENEDORES PARA DOCKER

-- Descarga de la imagen con la version correcta de la BBDD de MicrosoftSQL

-- docker pull mcr.microsoft.com/mssql/server:2019-CU21-ubuntu-20.04

-- Creacion del contenedor para la imagen de msSQL

-- docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=<YourStrong@Passw0rd>" -dp 1433:1433 mcr.microsoft.com/mssql/server:2019-CU21-ubuntu-20.04

-- Datos
---- Usuario: sa
---- Contraseña: <YourStrong@Passw0rd>


-- CONSULTAS PARA LA CREACION DE LA BASE DE DATOS

-- Creación de la base de datos
CREATE DATABASE CinemaDB;
GO
USE CinemaDB;
GO

-- Tabla JORNADA
CREATE TABLE JORNADA (
	IDJORNADA INT IDENTITY(1,1) PRIMARY KEY,
	FECHA DATE NOT NULL
);

-- Tabla PELICULAS
CREATE TABLE PELICULAS (
	IDPELICULA INT IDENTITY(1,1) PRIMARY KEY,
	TITULO NVARCHAR(250) NOT NULL,
	SINOPSIS NVARCHAR(MAX),
	DURACION INT,
	CATEGORIA NVARCHAR(250),
	DIRECTOR NVARCHAR(250),
	ANO INT,
	IMAGENURL NVARCHAR(MAX),
	PUNTUACION FLOAT
);



-- Insertar PELICULAS
INSERT INTO PELICULAS (TITULO, SINOPSIS, DURACION, CATEGORIA, DIRECTOR, ANO, IMAGENURL, PUNTUACION) 
VALUES 
('Inception', 'Un ladrón roba secretos a través de sueños.', 148, 'Ciencia ficción', 'Christopher Nolan', 2010, 'https://imagen.com/inception.jpg', 9),
('The Godfather', 'La historia de una familia mafiosa.', 175, 'Drama', 'Francis Ford Coppola', 1972, 'https://imagen.com/godfather.jpg', 10),
('Toy Story', 'Un juguete lidera una aventura para volver a casa.', 100, 'Animación', 'John Lasseter', 1995, 'https://imagen.com/toystory.jpg', 8);



-- Tabla SALA
CREATE TABLE SALA (
	IDSALA INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE NVARCHAR(50) NOT NULL,
	CAPACIDAD INT NOT NULL
);

-- Tabla TRAMOHORARIO
CREATE TABLE TRAMOHORARIO (
	IDTRAMOHORARIO INT IDENTITY(1,1) PRIMARY KEY,
	HORAINICIO NVARCHAR(44) NOT NULL,
	HORAFIN NVARCHAR(44) NOT NULL
);

-- Tabla SESION
CREATE TABLE SESION (
	IDSESION INT IDENTITY(1,1) PRIMARY KEY,
	IDPELICULA INT,
	IDSALA INT,
	IDTRAMOHORARIO INT,
	IDJORNADA INT,
	FOREIGN KEY (IDPELICULA) REFERENCES PELICULAS(IDPELICULA),
	FOREIGN KEY (IDSALA) REFERENCES SALA(IDSALA),
	FOREIGN KEY (IDTRAMOHORARIO) REFERENCES TRAMOHORARIO(IDTRAMOHORARIO),
	FOREIGN KEY (IDJORNADA) REFERENCES JORNADA(IDJORNADA)
);

-- TABLA USUARIOS
CREATE TABLE USUARIOS (
    IDUSUARIO INT IDENTITY(1,1) PRIMARY KEY,
    DNI NVARCHAR(15) NOT NULL,
    NOMBRE NVARCHAR(50) NOT NULL,
    APELLIDOS NVARCHAR(250) NOT NULL,
    EMAIL NVARCHAR(250) NOT NULL,
    FECHAREGISTRO DATETIME NOT NULL
);

-- Insert USUARIOS
INSERT INTO USUARIOS (DNI, NOMBRE, APELLIDOS, EMAIL, FECHAREGISTRO) 
VALUES 
('12345678A', 'Juan', 'Pérez Gómez', 'juan.perez@example.com', GETDATE()),
('87654321B', 'Ana', 'López Martínez', 'ana.lopez@example.com', GETDATE()),
('56781234C', 'Carlos', 'Fernández Ruiz', 'carlos.fernandez@example.com', GETDATE());


-- Tabla FACTURAS
CREATE TABLE FACTURAS (
	IDFACTURA UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	IDUSUARIO INT,
	FECHA DATETIME NOT NULL,
	TOTAL FLOAT NOT NULL,
	IDSESION INT,
	FOREIGN KEY (IDUSUARIO) REFERENCES USUARIOS(IDUSUARIO),
	FOREIGN KEY (IDSESION) REFERENCES SESION(IDSESION)
);

-- Tabla GRUPO_ASIENTOS
CREATE TABLE GRUPO_ASIENTOS (
	IDGRUPO INT IDENTITY(1,1) PRIMARY KEY,
	DESCRIPCION NVARCHAR(50),
	PRECIO FLOAT NOT NULL
);

-- Tabla ASIENTOS
CREATE TABLE ASIENTOS (
	IDASIENTO INT IDENTITY(1,1) PRIMARY KEY,
	IDSALA INT,
	NUM_ASIENTO INT NOT NULL,
	ESTADO CHAR(1) NOT NULL,
	IDGRUPO INT,
	FOREIGN KEY (IDSALA) REFERENCES SALA(IDSALA),
	FOREIGN KEY (IDGRUPO) REFERENCES GRUPO_ASIENTOS(IDGRUPO)
);

-- Tabla LINEA
CREATE TABLE LINEA (
	IDLINEA INT IDENTITY(1,1) PRIMARY KEY,
	IDFACTURA UNIQUEIDENTIFIER,
	IDASIENTO INT,
	FOREIGN KEY (IDFACTURA) REFERENCES FACTURAS(IDFACTURA),
	FOREIGN KEY (IDASIENTO) REFERENCES ASIENTOS(IDASIENTO)
);

-- Tabla OPINIONES
CREATE TABLE OPINIONES (
	IDOPINION INT IDENTITY(1,1) PRIMARY KEY,
	IDUSUARIO INT,
	IDPELICULA INT,
	COMENTARIO NVARCHAR(MAX),
	FECHACOMENTARIO DATETIME NOT NULL,
	FOREIGN KEY (IDUSUARIO) REFERENCES USUARIOS(IDUSUARIO),
	FOREIGN KEY (IDPELICULA) REFERENCES PELICULAS(IDPELICULA)
);

-- Insert OPINIONES
INSERT INTO OPINIONES (IDUSUARIO, IDPELICULA, COMENTARIO, FECHACOMENTARIO) 
VALUES 
(1, 1, 'Película increíble, te hace pensar.', GETDATE()),
(2, 2, 'Una obra maestra del cine.', GETDATE()),
(3, 3, 'Muy divertida y con mucho corazón.', GETDATE());
